---
title: "Plots for Application 4: mNGS results"
author: CZ ID
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r}
# global_options
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=T)
```

```{r include=FALSE}
library(tidyverse)
library(magrittr)
options(tibble.width = Inf)
options(scipen=999)
```


Define dataset. Note in this time course Day 12 had very few sequencing reads
```{r}
dataset_number = "App4"
```


Load metadata
```{r}
meta <- read.delim(paste0("dataset_ID_metadata_", dataset_number, ".tsv")) 

# which samples to plot in heatmap
meta_sample = meta %>% filter(!str_detect(metadata, "water")) 
```


Load and prep mNGS table
```{r}
filename_list = list.files(path = "./amr_paper_2023_5929", pattern="App4.*_taxon_report.csv", full.names = T) 

file_list = lapply(filename_list, read.csv) 

names(file_list) = stringr::str_replace(basename(filename_list), pattern = "_taxon_report.csv", replacement = "")

mgs = lapply(names(file_list), function(nm) mutate(file_list[[nm]], sample_name=str_sub(nm, end = -8))) %>% purrr::reduce(bind_rows) %>% 
    filter(tax_level==1)

# Respiratory syncytial virus is not what we're after. In NCBI it's grouped under Human orthopneumovirus. The reads for Respiratory syncytial virus are actually under non-genus-specific reads in family Pneumoviridae
mgs1_pseu = left_join(meta_sample, filter(mgs, name%in%c("Pseudomonas aeruginosa","Human orthopneumovirus"))) %>%
    mutate(nt_rpm = ifelse(is.na(nt_rpm), 0, nt_rpm), nt_count = ifelse(is.na(nt_count), 0, nt_count), group = ifelse(str_detect(metadata, "culture"), "culture", "mNGS"))

ll=select(mgs1_pseu, sample_name, name, metadata, nt_count, nt_rpm)

# normal scale
p0 = ggplot(mgs1_pseu) + 
    geom_bar(aes(x=fct_inorder(metadata), y=nt_rpm), stat = "identity") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    theme(legend.position="none",
          axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank(),
          axis.text.y = element_text(size=8), axis.ticks.y=element_blank(),
          panel.spacing = unit(0.3,"lines"),
          strip.text.y = element_text(size = 10, hjust=0, angle=0),
          plot.caption = element_text(hjust=1),
          panel.grid = element_blank()) +
    facet_grid(rows=vars(name), scales = "free_y", labeller = label_wrap_gen(width=5)) 

ggsave(paste0("plot_",  dataset_number, "_mNGS.pdf"), width = 4, height = 3)

```


```{r}
sessionInfo()
```
